### ISSUE TITLE
Error in Meteor 1.2.0.2 - ReferenceError: google is not defined

### ISSUE THREAD

**Issue by jamiecollinson** [dburles/meteor-google-maps#82]
Hoping someone can help - I have an existing project which I'm in the process of upgrading to Meteor 1.2.

I've successfully done a meteor update and have my project working, except for one problem I'm experiencing with `meteor-google-maps` - whenever I visit a template which contains one of my maps I get the following error:

```
ReferenceError: google is not defined
    at [object Object].<anonymous> (http://localhost:3000/packages/meteor:/💻app/packages/dburles_google-maps/packages/dburles_google-maps.js:148:1)
    at http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3302:1
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3643:1)
    at fireCallbacks (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3298:1)
    at [object Object].<anonymous> (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3404:1)
    at fireCallbacks (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:1924:1)
    at Object.Tracker.nonreactive (http://localhost:3000/packages/meteor:/💻app/packages/tracker/tracker.js:589:1)
    at http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:1921:1
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:2183:1)
    at Object.Blaze._fireCallbacks (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:1920:1) undefined
```

This then seems to cause some knock-on issues with Blaze, but I only see them preceded by the above error, so I'm fairly sure they're triggered by it. Some DOM elements become unresponsive and I get the following console error:

```
Exception from Tracker afterFlush function: undefined

Error: Must be attached
    at [object Object].DOMRange.firstNode (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:446:1)
    at [object Object].view.templateInstance (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3354:1)
    at [object Object].<anonymous> (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3391:1)
    at http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:1752:1
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:2183:1)
    at http://localhost:3000/packages/meteor:/💻app/packages/blaze/packages/blaze.js:1751:1
    at Object.Tracker._runFlush (http://localhost:3000/packages/meteor:/💻app/packages/tracker/tracker.js:497:1)
    at Object.Tracker.flush (http://localhost:3000/packages/meteor:/💻app/packages/tracker/tracker.js:441:1)
    at [object Object].Router._invalidateTracker (http://localhost:3000/packages/meteor:/💻app/packages/kadira_flow-router/client/router.js:467:1)
    at afterAllTriggersRan (http://localhost:3000/packages/meteor:/💻app/packages/kadira_flow-router/client/router.js:92:1) undefined
```

I'm guessing this is related to some update to Blaze? Has anyone come across this or have any pointers on how to resolve? 

At the moment it's the only blocker to me completing the upgrade, so I'd be very grateful for any help.

**Comment by MaxGuitet** [comment]
To add more information on this issue (I'm working with @jamiecollinson on the project). We've investigated a bit and it turns out the problem comes from the onDestroyed event. Commenting out the line 116 
`google.maps.event.clearInstanceListeners(GoogleMaps.maps[this._name].instance);`
solves the error. We found that  GoogleMaps.maps[this._name] was undefined because  this._name was undefined. Replacing it by this.data.name solved partially the problem but we still have the `Error: Must be attached` part.

Hope this will help.

**Comment by dburles** [comment]
Hey guys, I've not seen any issues with 1.2 so far, I've just updated the example apps to 1.2.0.2 and they're running okay. Might there be some other influence? are you able to reproduce the issue on a stripped down version of the application (or a brand new one)? if so, that would be super helpful

**Comment by dburles** [comment]
Just had a quick mess around and I have reproduced the issue, I'll hopefully have a fix up soon, thanks

**Comment by dburles** [comment]
I've just released 1.1.5, please let me know if it fixes the issue

**Comment by MaxGuitet** [comment]
It seems to have solved the issue indeed. Thanks very much for that!

**Comment by dburles** [comment]
Great!
